import { NextResponse } from "next/server";
import { PDFDocument, rgb } from "pdf-lib";
import Transaction from "@/models/Transaction";
import BudgetGoal from "@/models/BudgetGoal";
import { connectDB } from "@/lib/dbConfig";
import { verifyToken } from "@/lib/auth";
import mongoose from "mongoose";

import * as fontkit from "fontkit";
import { readFileSync } from "fs";
import path from "path";

export async function POST(req) {
  try {
    await connectDB();

    const tokenData = await verifyToken();
    if (!tokenData) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { month, year, insights } = await req.json();

    if (!month || !year || !insights) {
      return NextResponse.json(
        { error: "Month, year & insights required" },
        { status: 400 }
      );
    }

    const userId = tokenData._id;

    const from = new Date(year, month - 1, 1);
    const to = new Date(year, month, 0, 23, 59, 59);

    const transactions = await Transaction.find({
      userId: new mongoose.Types.ObjectId(userId),
      date: { $gte: from, $lte: to },
    }).lean();

    const goals = await BudgetGoal.find({
      userId: new mongoose.Types.ObjectId(userId),
      month,
      year,
    }).lean();

    const totalSpent = transactions.reduce(
      (sum, t) => sum + Number(t.amount),
      0
    );

    const categoryTotals = {};
    transactions.forEach((t) => {
      const c = t.category.toLowerCase();
      categoryTotals[c] = (categoryTotals[c] || 0) + Number(t.amount);
    });

    const pdfDoc = await PDFDocument.create();
    pdfDoc.registerFontkit(fontkit);

    let page = pdfDoc.addPage([600, 800]);
    const pageWidth = 600;
    const marginLeft = 50;
    const marginRight = 50;
    const usableWidth = pageWidth - marginLeft - marginRight;

    const fontPath = path.join(
      process.cwd(),
      "public",
      "fonts",
      "NotoSans-Regular.ttf"
    );
    const fontBytes = readFileSync(fontPath);
    const unicodeFont = await pdfDoc.embedFont(fontBytes);

    let y = 760;

    const wrapText = (text, maxWidth, font, size) => {
      const words = text.split(" ");
      let lines = [];
      let current = "";

      for (const word of words) {
        const width = font.widthOfTextAtSize(
          current ? current + " " + word : word,
          size
        );

        if (width > maxWidth) {
          lines.push(current);
          current = word;
        } else {
          current = current ? current + " " + word : word;
        }
      }

      if (current) lines.push(current);
      return lines;
    };

    const write = (text, size = 12) => {
      const lines = wrapText(text, usableWidth, unicodeFont, size);

      for (const line of lines) {
        if (y < 40) {
          page = pdfDoc.addPage([600, 800]);
          y = 760;
        }

        page.drawText(line, {
          x: marginLeft,
          y,
          size,
          font: unicodeFont,
          color: rgb(0, 0, 0),
        });

        y -= size + 5;
      }
    };

    write("Monthly Spending Report", 20);
    write(`Month: ${month}   Year: ${year}`, 14);

    y -= 10;
    write("Total Spending", 16);
    write(`₹${totalSpent.toFixed(2)}`, 14);

    y -= 10;
    write("Category Breakdown:", 16);

    for (const [cat, amt] of Object.entries(categoryTotals)) {
      write(`${cat}: ₹${amt.toFixed(2)}`, 12);
    }

    y -= 10;
    write("Budget Controls:", 16);

    if (goals.length === 0) {
      write("No limits set for this month.");
    } else {
      goals.forEach((g) => {
        const spent = categoryTotals[g.category] || 0;
        const diff = spent - g.limit;

        let status =
          diff > 0
            ? `Exceeded by ₹${diff.toFixed(2)}`
            : `Within limit (Remaining ₹${Math.abs(diff).toFixed(2)})`;

        write(
          `${g.category.toUpperCase()}: Limit ₹${
            g.limit
          } — Spent ₹${spent.toFixed(2)} → ${status}`,
          12
        );
      });
    }

    y -= 20;
    write("AI Insights:", 18);

    const lines = insights.split("\n");
    lines.forEach((line) => {
      if (line.trim().length > 0) {
        write(line, 12);
      }
    });

    y -= 10;
    write("Generated by SpendWise AI", 10);

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename=report-${month}-${year}.pdf`,
      },
    });
  } catch (error) {
    console.error("PDF Error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF", message: error.message },
      { status: 500 }
    );
  }
}
